version: '3'
services:
  postgres:
    image: postgres:13.3-alpine
    command: -c max_locks_per_transaction=128 -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c fsync=off # fsync speed up things, but don't use for production, can result in unrecoverable data corruption in the event of a power failure or system crash
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  bundle:
  postgres:
  elasticsearch:

networks:
  redis-replication:
    driver: bridge

